language: generic

sudo: required
services:
  - docker

# Build client test image
before_install:
  - docker build -t joxmar/client-test ./client

# Run tests on client test image
script:
  - docker run -e CI=true joxmar/client-test yarn test
# after_success:
#   # Build production images
#   - docker build -t joxmar/tweeter-client -f ./client/Dockerfile.prod ./client
#   - docker build -t joxmar/tweeter-server -f ./server/Dockerfile.prod ./server
#   - docker build -t joxmar/tweeter-nginx -f ./nginx/Dockerfile.prod ./nginx
#   # Log into the docker CLI
#   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
#   # Push images to docker hub
#   - docker push joxmar/tweeter-client
#   - docker push joxmar/tweeter-server
#   - docker push joxmar/tweeter-nginx
# deploy:
#   edge: true
#   provider: elasticbeanstalk
#   region: us-west-2
#   app: multi-docker
#   env: MultiDocker-env
#   bucket_name: elasticbeanstalk-us-west-2-799881107835
#   bucket_path: MultiDocker-env
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY
